src/Entity/MissionCombat.php
<?php

namespace App\Entity;

use App\Repository\MissionCombatRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: MissionCombatRepository::class)]
class MissionCombat
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Nom = null;

    #[ORM\Column(length: 255)]
    private ?string $Code = null;

    #[ORM\OneToMany(mappedBy: 'missionCombat', targetEntity: Game::class)]
    private Collection $games;

    public function __construct()
    {
        $this->games = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): static
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getCode(): ?string
    {
        return $this->Code;
    }

    public function setCode(string $Code): static
    {
        $this->Code = $Code;

        return $this;
    }

    /**
     * @return Collection<int, Game>
     */
    public function getGames(): Collection
    {
        return $this->games;
    }

    public function addGame(Game $game): static
    {
        if (!$this->games->contains($game)) {
            $this->games->add($game);
            $game->setMissionCombat($this);
        }

        return $this;
    }

    public function removeGame(Game $game): static
    {
        if ($this->games->removeElement($game)) {
            // set the owning side to null (unless already changed)
            if ($game->getMissionCombat() === $this) {
                $game->setMissionCombat(null);
            }
        }

        return $this;
    }
}

src/Controller/RankingController.php
<?php

namespace App\Controller;

use App\Entity\Belligerant;
use App\Entity\Game;
use App\Entity\Joueur;
use App\Entity\Rank;
use App\Service\EloManager;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class RankingController extends AbstractController
{   
    public function __construct(private EntityManagerInterface $entityManager, private EloManager $eloMananger)
    {
        
    }

    #[Route('/ranking/regenerate', name: 'ranking_regenerate')]
    public function regenerate(): Response
    {   

        $this->eloMananger->updateAllJoueurs();

        return $this->redirect('/ranking');
    }

    #[Route('/ranking', name: 'app_ranking')]
    public function index(): Response
    {   
        $joueurs = $this->entityManager->getRepository(Joueur::class)->findAll();
        $joueurRanked = $this->entityManager->getRepository(Joueur::class)->findAllSortedByEloRanking();

        $joueurGames = [];
        foreach ($joueurs as $joueur) {
            $lastGame = $this->entityManager->getRepository(Game::class)->lastGame($joueur);
            $joueurGames[$joueur->getId()] = $this->entityManager->getRepository(Game::class)->countGames($joueur);
            $joueurGames[$joueur->getId()]['lastGame'] = $lastGame === null? null : $lastGame->getDate();
            $joueurGames[$joueur->getId()]['ties'] = $this->entityManager->getRepository(Game::class)->countTies($joueur);
            $joueurGames[$joueur->getId()][1] = $this->entityManager->getRepository(Rank::class)->findTournamentNamesForPosition($joueur,1);
            $joueurGames[$joueur->getId()][2] = $this->entityManager->getRepository(Rank::class)->findTournamentNamesForPosition($joueur,2);
            $joueurGames[$joueur->getId()][3] = $this->entityManager->getRepository(Rank::class)->findTournamentNamesForPosition($joueur,3);
        }
        $joueursRankedZits = $this->entityManager->getRepository(Joueur::class)->findAllSortedByZitsRanking();


        return $this->render('ranking/index.html.twig', [
            'controller_name' => 'RankingController',
            'joueursRanked' => $joueurRanked,
            'joueurGames' => $joueurGames,
            'joueursRankedZits' => $joueursRankedZits
        ]);
    }
}

templates/ranking/index.html.twig
{% extends 'base.html.twig' %}

{% block pageJavascripts %}
    <script type="application/javascript">
    $(window).on('load',function(){
        $("#tabs").tabs();
    });
    </script>
{% endblock %}

{% block title %}Caestats - classement ELO des joueurs{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="content">
    <h1>Classements des joueurs</h1>

    <div id="tabs">
        <ul>
            <li><a href="#tabs-1">Elo</a></li>
            <li><a href="#tabs-2">ZITS</a></li>
        </ul>
    <div id="tabs-1">
        <table>
            <tr>
                <th>Rang</th>
                <th>Elo</th>
                <th>Nom</th>
                <th>Winrate</th>
                <th>V - E - D - T</th>
                <th>Dernière partie</th>
            </tr>
                
            {% for joueur in joueursRanked %}
                <tr style="{% if loop.index % 2 == 0 %}background-color:rgb(40, 135, 140,0.5);{% else %}background-color:rgb(210, 149, 50,0.5);{% endif %}">
                    <td>{{loop.index}}</td>
                    <td>{{joueur.elo}}</td>
                    <td><a href="{{ path('app_stats_game', {'joueurId' : joueur.id}) }}">{{joueur.nom}}</a></td>
                    <td>{{((joueurGames[joueur.id]['totalWins']/joueurGames[joueur.id]['total'])*100)|round(1)}}% </td>
                    <td>{{joueurGames[joueur.id]['totalWins']}}V - {{joueurGames[joueur.id]['ties']}}E - {{joueurGames[joueur.id]['total'] - (joueurGames[joueur.id]['totalWins']+joueurGames[joueur.id]['ties'])}}D - {{joueurGames[joueur.id]['total']}}T</td>
                    <td>{{joueurGames[joueur.id]['lastGame']|date("d/m/Y")}} </td>
                </tr>
            {% endfor %}

        </table>
    </div>
    <div id="tabs-2">
        <table>
            <tr>
                <th>Rang</th>
                <th>ZITS</th>
                <th>Nom</th>
                <th>Trophée</th>
            </tr>
                
            {% for joueur in joueursRankedZits %}
                <tr style="{% if loop.index % 2 == 0 %}background-color:rgb(40, 135, 140,0.5);{% else %}background-color:rgb(210, 149, 50,0.5);{% endif %}">
                    <td>{{loop.index}}</td>
                    <td>{{joueur.zits}}</td>
                    <td><a href="{{ path('app_zits_joueur_detail', {'joueurId' : joueur.id}) }}">{{joueur.nom}}</a></td>
                    <td>
                        {% if joueurGames[joueur.id][1] is not empty %}
                            {% for tournament in joueurGames[joueur.id][1] %}
                                <img src="{{asset('images/cup_1.png')}}" title="{{tournament['nom']}}" style="max-width:30px;vertical-align: middle;"/>
                            {% endfor %}
                        {% endif %}
                        {% if joueurGames[joueur.id][2] is not empty %}
                            {% for tournament in joueurGames[joueur.id][2] %}
                                <img src="{{asset('images/cup_2.png')}}" title="{{tournament['nom']}}" style="max-width:30px;vertical-align: middle;"/>
                            {% endfor %}
                        {% endif %}
                        {% if joueurGames[joueur.id][3] is not empty %}
                            {% for tournament in joueurGames[joueur.id][3] %}
                                <img src="{{asset('images/cup_3.png')}}" title="{{tournament['nom']}}" style="max-width:30px;vertical-align: middle;"/>
                            {% endfor %}
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}

        </table>
        <div style="font-size:0.8em;font-style:italic;margin-top:20px;">
            ZITS (Ze Incredible Tournament System) est un système de classement en Béta qui met en avant les participations et victoires aux tournois plutôt que les résultats des rencontres entre les joueurs. C'est un système "à la t3" qui récompense la participation et les bons résulats à des tournois.
            <br/>
            Le principe est que chaque tournoi a une cote influencée par:
            <ul>
                <li>Le nombre de joueur (plus il y a de joueurs, plus le tournoi a une cote élevée)</li>
                <li>La moyenne de ZITS de chaque joueur par rapport à la moyenne nationale (plus le niveau est elevé dans le tournoi, plus la cote est élevée)</li>
                <li>Le temps qui passe (plus le tournoi est vieux, moins il fait de point. La cote vaut 0 si le tournoi a plus d'un an)</li>
            </ul>
            Ensuite, la cote donne un certains nombre de point aux joueurs. Plus le joueur est mieux placé dans le tournoi, plus il prend de point (prime dégressive pour les 3 premiers).
            <br/>
            Le détail des calculs seront publiées une fois qu'une période de "tweak" sera terminée.
        </div>
    </div>
</div>
    
{% endblock %}