src/Entity/MissionCombat.php
<?php

namespace App\Entity;

use App\Repository\MissionCombatRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: MissionCombatRepository::class)]
class MissionCombat
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Nom = null;

    #[ORM\Column(length: 255)]
    private ?string $Code = null;

    #[ORM\OneToMany(mappedBy: 'missionCombat', targetEntity: Game::class)]
    private Collection $games;

    public function __construct()
    {
        $this->games = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): static
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getCode(): ?string
    {
        return $this->Code;
    }

    public function setCode(string $Code): static
    {
        $this->Code = $Code;

        return $this;
    }

    /**
     * @return Collection<int, Game>
     */
    public function getGames(): Collection
    {
        return $this->games;
    }

    public function addGame(Game $game): static
    {
        if (!$this->games->contains($game)) {
            $this->games->add($game);
            $game->setMissionCombat($this);
        }

        return $this;
    }

    public function removeGame(Game $game): static
    {
        if ($this->games->removeElement($game)) {
            // set the owning side to null (unless already changed)
            if ($game->getMissionCombat() === $this) {
                $game->setMissionCombat(null);
            }
        }

        return $this;
    }
}

src/Controller/Resultats/ResultatDTO.php
<?php
/** src/Controller/ResultatController.php */ 
namespace App\Controller\Resultats;

use App\Entity\Game;
use App\Entity\Guilde;
use App\Entity\Joueur;
use App\Entity\MissionControle;
use App\Entity\MissionCombat;
use App\Entity\Personnage;
use App\Entity\Tournoi;

class ResultatDTO
{

    private ?int $__gameId = null;
    private ?\DateTimeInterface $_date = null;
    private Joueur $_joueur1;
    private Joueur $_joueur2;
    private ?int $_scoreJoueur1;
    private ?int $_scoreJoueur2;
    private ?bool $rixe;
    private ?bool $noRanking;
    private ?bool $noStats;
    private ?Tournoi $__tournoi;
    private ?int $__ronde;
    private MissionControle $_missionControle;
    private MissionCombat $_missionCombat;
    private Guilde $_guilde1;
    private Guilde $_guilde2;
    private ?Personnage $_personnage1Joueur1 = null;
    private ?Personnage $_personnage2Joueur1 = null;
    private ?Personnage $_personnage3Joueur1 = null;
    private ?Personnage $_personnage4Joueur1 = null;
    private ?Personnage $_personnage5Joueur1 = null;
    private ?Personnage $_personnage1Joueur2 = null;
    private ?Personnage $_personnage2Joueur2 = null;
    private ?Personnage $_personnage3Joueur2 = null;
    private ?Personnage $_personnage4Joueur2 = null;
    private ?Personnage $_personnage5Joueur2 = null;


    public function __construct(?Game $game){
        
        if($game === null){
            return;
        }

        $this->setGameId($game->getId());
        $this->setDate($game->getDate());
        $this->setJoueur1($game->getBelligerant1()->getJoueur());
        $this->setJoueur2($game->getBelligerant2()->getJoueur());
        $this->setGuilde1($game->getBelligerant1()->getCompo()->getGuilde());
        $this->setGuilde2($game->getBelligerant2()->getCompo()->getGuilde());
        $this->setScoreJoueur1($game->getBelligerant1()->getScore());
        $this->setScoreJoueur2($game->getBelligerant2()->getScore());
        $this->setRixe($game->isRixe());
        $this->setNoRanking($game->isNoRanking());
        $this->setNoStats($game->isNoStats());
        $this->setTournoi($game->getTournoi());
        $this->setRonde($game->getRonde());
        $this->setMissionControle($game->getMissionControle());
        $this->setMissionCombat($game->getMissionCombat());
        $this->setPersonnage1Joueur1($game->getBelligerant1()->getCompo()->getPersonnages()->get(0));
        $this->setPersonnage2Joueur1($game->getBelligerant1()->getCompo()->getPersonnages()->get(1));
        $this->setPersonnage3Joueur1($game->getBelligerant1()->getCompo()->getPersonnages()->get(2));
        $this->setPersonnage4Joueur1($game->getBelligerant1()->getCompo()->getPersonnages()->get(3));
        $this->setPersonnage5Joueur1($game->getBelligerant1()->getCompo()->getPersonnages()->get(4));
        $this->setPersonnage1Joueur2($game->getBelligerant2()->getCompo()->getPersonnages()->get(0));
        $this->setPersonnage2Joueur2($game->getBelligerant2()->getCompo()->getPersonnages()->get(1));
        $this->setPersonnage3Joueur2($game->getBelligerant2()->getCompo()->getPersonnages()->get(2));
        $this->setPersonnage4Joueur2($game->getBelligerant2()->getCompo()->getPersonnages()->get(3));
        $this->setPersonnage5Joueur2($game->getBelligerant2()->getCompo()->getPersonnages()->get(4));
    }


    /**
     * Get the value of __gameId
     */
    public function getGameId(): ?int
    {
        return $this->__gameId;
    }

    /**
     * Set the value of __gameId
     */
    public function setGameId(?int $__gameId): self
    {
        $this->__gameId = $__gameId;

        return $this;
    }

    /**
     * Get the value of _date
     */
    public function getDate(): ?\DateTimeInterface
    {
        return $this->_date;
    }

    /**
     * Set the value of _date
     */
    public function setDate(?\DateTimeInterface $_date): self
    {
        $this->_date = $_date;

        return $this;
    }

    /**
     * Get the value of _joueur1
     */
    public function getJoueur1(): Joueur
    {
        return $this->_joueur1;
    }

    /**
     * Set the value of _joueur1
     */
    public function setJoueur1(Joueur $_joueur1): self
    {
        $this->_joueur1 = $_joueur1;

        return $this;
    }

    /**
     * Get the value of _joueur2
     */
    public function getJoueur2(): Joueur
    {
        return $this->_joueur2;
    }

    /**
     * Set the value of _joueur2
     */
    public function setJoueur2(Joueur $_joueur2): self
    {
        $this->_joueur2 = $_joueur2;

        return $this;
    }


    /**
     * Get the value of _scoreJoueur1
     */
    public function getScoreJoueur1(): ?int
    {
        return $this->_scoreJoueur1;
    }

    /**
     * Set the value of _scoreJoueur1
     */
    public function setScoreJoueur1(?int $_scoreJoueur1): self
    {
        $this->_scoreJoueur1 = $_scoreJoueur1;

        return $this;
    }

    /**
     * Get the value of _scoreJoueur2
     */
    public function getScoreJoueur2(): ?int
    {
        return $this->_scoreJoueur2;
    }

    /**
     * Set the value of _scoreJoueur2
     */
    public function setScoreJoueur2(?int $_scoreJoueur2): self
    {
        $this->_scoreJoueur2 = $_scoreJoueur2;

        return $this;
    }

    /**
     * Get the value of rixe
     */
    public function isRixe(): ?bool
    {
        return $this->rixe;
    }

    /**
     * Set the value of rixe
     */
    public function setRixe(?bool $rixe): self
    {
        $this->rixe = $rixe;

        return $this;
    }

    /**
     * Get the value of _missionControle
     */
    public function getMissionControle(): MissionControle
    {
        return $this->_missionControle;
    }

    /**
     * Set the value of _missionControle
     */
    public function setMissionControle(MissionControle $_missionControle): self
    {
        $this->_missionControle = $_missionControle;

        return $this;
    }

    /**
     * Get the value of _missionCombat
     */
    public function getMissionCombat(): MissionCombat
    {
        return $this->_missionCombat;
    }

    /**
     * Set the value of _missionCombat
     */
    public function setMissionCombat(MissionCombat $_missionCombat): self
    {
        $this->_missionCombat = $_missionCombat;

        return $this;
    }

    /**
     * Get the value of _guilde1
     */
    public function getGuilde1(): Guilde
    {
        return $this->_guilde1;
    }

    /**
     * Set the value of _guilde1
     */
    public function setGuilde1(Guilde $_guilde1): self
    {
        $this->_guilde1 = $_guilde1;

        return $this;
    }

    /**
     * Get the value of _guilde2
     */
    public function getGuilde2(): Guilde
    {
        return $this->_guilde2;
    }

    /**
     * Set the value of _guilde2
     */
    public function setGuilde2(Guilde $_guilde2): self
    {
        $this->_guilde2 = $_guilde2;

        return $this;
    }

    /**
     * Get the value of _personnage1Joueur1
     */
    public function getPersonnage1Joueur1(): ?Personnage
    {
        return $this->_personnage1Joueur1;
    }

    /**
     * Set the value of _personnage1Joueur1
     */
    public function setPersonnage1Joueur1(?Personnage $_personnage1Joueur1): self
    {
        $this->_personnage1Joueur1 = $_personnage1Joueur1;

        return $this;
    }

    /**
     * Get the value of _personnage2Joueur1
     */
    public function getPersonnage2Joueur1(): ?Personnage
    {
        return $this->_personnage2Joueur1;
    }

    /**
     * Set the value of _personnage2Joueur1
     */
    public function setPersonnage2Joueur1(?Personnage $_personnage2Joueur1): self
    {
        $this->_personnage2Joueur1 = $_personnage2Joueur1;

        return $this;
    }

    /**
     * Get the value of _personnage3Joueur1
     */
    public function getPersonnage3Joueur1(): ?Personnage
    {
        return $this->_personnage3Joueur1;
    }

    /**
     * Set the value of _personnage3Joueur1
     */
    public function setPersonnage3Joueur1(?Personnage $_personnage3Joueur1): self
    {
        $this->_personnage3Joueur1 = $_personnage3Joueur1;

        return $this;
    }

    /**
     * Get the value of _personnage4Joueur1
     */
    public function getPersonnage4Joueur1(): ?Personnage
    {
        return $this->_personnage4Joueur1;
    }

    /**
     * Set the value of _personnage4Joueur1
     */
    public function setPersonnage4Joueur1(?Personnage $_personnage4Joueur1): self
    {
        $this->_personnage4Joueur1 = $_personnage4Joueur1;

        return $this;
    }

    /**
     * Get the value of _personnage5Joueur1
     */
    public function getPersonnage5Joueur1(): ?Personnage
    {
        return $this->_personnage5Joueur1;
    }

    /**
     * Set the value of _personnage5Joueur1
     */
    public function setPersonnage5Joueur1(?Personnage $_personnage5Joueur1): self
    {
        $this->_personnage5Joueur1 = $_personnage5Joueur1;

        return $this;
    }

    /**
     * Get the value of _personnage1Joueur2
     */
    public function getPersonnage1Joueur2(): ?Personnage
    {
        return $this->_personnage1Joueur2;
    }

    /**
     * Set the value of _personnage1Joueur2
     */
    public function setPersonnage1Joueur2(?Personnage $_personnage1Joueur2): self
    {
        $this->_personnage1Joueur2 = $_personnage1Joueur2;

        return $this;
    }

    /**
     * Get the value of _personnage2Joueur2
     */
    public function getPersonnage2Joueur2(): ?Personnage
    {
        return $this->_personnage2Joueur2;
    }

    /**
     * Set the value of _personnage2Joueur2
     */
    public function setPersonnage2Joueur2(?Personnage $_personnage2Joueur2): self
    {
        $this->_personnage2Joueur2 = $_personnage2Joueur2;

        return $this;
    }

    /**
     * Get the value of _personnage3Joueur2
     */
    public function getPersonnage3Joueur2(): ?Personnage
    {
        return $this->_personnage3Joueur2;
    }

    /**

templates/resultat/edit.html.twig
{% extends 'base.html.twig' %}

{% block pageJavascripts %}

    <script type="application/javascript">
    $(window).on('load',function(){

    var gamerId = '{{form.vars.value.gameId}}';

    $("#form_guilde1").change(function(){
        var _this = $(this);
        changeGuilde(_this.val(),"1");
    });
    $("#form_guilde1").change();
    
    $("#form_guilde2").change(function(){
        var _this = $(this);
        changeGuilde(_this.val(),"2");
    });
    $("#form_guilde2").change();

    $("#form_rixe").change(function(){
        var _this = $(this);
        if(_this.is(':checked')){
            $('#form_personnage5Joueur1').attr('disabled','disabled');
            $('#form_personnage5Joueur2').attr('disabled','disabled');
        }
        else{
            $('#form_personnage5Joueur1').removeAttr('disabled');
            $('#form_personnage5Joueur2').removeAttr('disabled');
        }
    });
    $('#form_rixe').change();

    $("#form_vainqueur1").change(function(){
        var _this = $(this);
        if(_this.is(':checked')){
             if(_this.is(':checked')){
                $('#form_vainqueur2').prop("checked",false);
            }
        }
    });

      $("#form_vainqueur2").change(function(){
        var _this = $(this);
        if(_this.is(':checked')){
             if(_this.is(':checked')){
                $('#form_vainqueur1').prop("checked",false);
            }
        }
    });

    $('#form_tournoi').change(function(){
        var _this = $(this);
        if(_this.val() != ''){
            $('#form_ronde').removeAttr('disabled');
        }
        else {
            $('#form_ronde').attr('disabled','disabled');
        }
    });
    $("#form_tournoi").change();

});

var changeGuilde = function(guilde,numeroJoueur){
    $.ajax({
        url : "/personnages?guildeId="+guilde,
        success(data, textStatus, jqXHR){
           var select = $('#form_personnage1Joueur'+numeroJoueur);
           select.html('');
            $.each(JSON.parse(data),function(index, iter){
            select.append("<option value='"+iter.id+"'>"+iter.nom+"</option>");
           });
           select = $('#form_personnage2Joueur'+numeroJoueur);
           select.html('');
            $.each(JSON.parse(data),function(index, iter){
            select.append("<option value='"+iter.id+"'>"+iter.nom+"</option>");
           });
           select = $('#form_personnage3Joueur'+numeroJoueur);
           select.html('');
            $.each(JSON.parse(data),function(index, iter){
            select.append("<option value='"+iter.id+"'>"+iter.nom+"</option>");
           });
           select = $('#form_personnage4Joueur'+numeroJoueur);
           select.html('');
            $.each(JSON.parse(data),function(index, iter){
            select.append("<option value='"+iter.id+"'>"+iter.nom+"</option>");
           });
           select = $('#form_personnage5Joueur'+numeroJoueur);
           select.html('');
            select.append("<option value=''></option>");
            $.each(JSON.parse(data),function(index, iter){
                select.append("<option value='"+iter.id+"'>"+iter.nom+"</option>");
            });
           if(numeroJoueur='1'){
            {% if form.vars.value.personnage1Joueur1 is not null %}
                $('#form_personnage1Joueur1').children("option[value={{form.vars.value.personnage1Joueur1.id}}]").attr("selected","selected");
            {% endif %}
            {% if form.vars.value.personnage2Joueur1 is not null %}
                $('#form_personnage2Joueur1').children("option[value={{form.vars.value.personnage2Joueur1.id}}]").attr("selected","selected");
            {% endif %}
            {% if form.vars.value.personnage3Joueur1 is not null %}
                $('#form_personnage3Joueur1').children("option[value={{form.vars.value.personnage3Joueur1.id}}]").attr("selected","selected");
            {% endif %}
            {% if form.vars.value.personnage4Joueur1 is not null %}
                $('#form_personnage4Joueur1').children("option[value={{form.vars.value.personnage4Joueur1.id}}]").attr("selected","selected");
            {% endif %}
            {% if form.vars.value.personnage5Joueur1 is not null %}
                $('#form_personnage5Joueur1').children("option[value={{form.vars.value.personnage5Joueur1.id}}]").attr("selected","selected");
            {% endif %}
           }
           if(numeroJoueur='2'){
            {% if form.vars.value.personnage1Joueur1 is not null %}
                $('#form_personnage1Joueur2').children("option[value={{form.vars.value.personnage1Joueur2.id}}]").attr("selected","selected");
            {% endif %}
            {% if form.vars.value.personnage2Joueur1 is not null %}
                $('#form_personnage2Joueur2').children("option[value={{form.vars.value.personnage2Joueur2.id}}]").attr("selected","selected");
            {% endif %}
            {% if form.vars.value.personnage3Joueur1 is not null %}
                $('#form_personnage3Joueur2').children("option[value={{form.vars.value.personnage3Joueur2.id}}]").attr("selected","selected");
            {% endif %}
            {% if form.vars.value.personnage4Joueur1 is not null %}
                $('#form_personnage4Joueur2').children("option[value={{form.vars.value.personnage4Joueur2.id}}]").attr("selected","selected");
            {% endif %}
            {% if form.vars.value.personnage5Joueur1 is not null %}
                $('#form_personnage5Joueur2').children("option[value={{form.vars.value.personnage5Joueur2.id}}]").attr("selected","selected");
            {% endif %}
           }
        }
    });
};

</script>

{% endblock %}

{% block body%} 

    <div class="content">
        {% if form.vars.value.gameId == null %}
            Création d'une partie 
        {% else %}
            Modification d'une partie
        {% endif %}


        {{ form_start(form) }}
            {{ form_row(form.date) }}
            {{ form_row(form.tournoi) }} 
            {{ form_row(form.ronde) }} 
            {{ form_row(form.rixe) }}
            {{ form_row(form.noRanking) }}
            {{ form_row(form.noStats) }}
            {{ form_row(form.missionControle) }}   
            {{ form_row(form.missionCombat) }} 
            <br/>
            <div style="display: inline-block;width:400px;">
            {{ form_row(form.joueur1) }} 
            {{ form_row(form.scoreJoueur1) }}
            {{ form_row(form.guilde1) }}
            {{ form_row(form.personnage1Joueur1) }}
            {{ form_row(form.personnage2Joueur1) }}
            {{ form_row(form.personnage3Joueur1) }}
            {{ form_row(form.personnage4Joueur1) }}
            {{ form_row(form.personnage5Joueur1) }}
            </div>
            <div style="display: inline-block;width:400px;">
            {{ form_row(form.joueur2) }} 
            {{ form_row(form.scoreJoueur2) }}
            {{ form_row(form.guilde2) }}
            {{ form_row(form.personnage1Joueur2) }}
            {{ form_row(form.personnage2Joueur2) }}
            {{ form_row(form.personnage3Joueur2) }}
            {{ form_row(form.personnage4Joueur2) }}
            {{ form_row(form.personnage5Joueur2) }} 
            </div>

        {{ form_end(form) }}

        <a href="{{ path('resultat_list') }}">< Retour</a>
    </div>
{% endblock %}

templates/resultat/index.html.twig
{% extends 'base.html.twig' %}

{% block body%} 

<div class="content">
    <table>
        <tr>
            <th>
                Joueur 1 vs Joueur 2
            </th>
            <th>
                Guilde 1 vs Guilde 2
            </th>
            <th>
                Compo1 vs Compo 2
            </th>
            <th>
                Date
            </th>
            <th>
                Action
            </th>
        </tr>

        {% for game in games %}
            <tr>
                <td>
                    {{game.belligerant1.joueur.nom}} vs {{game.belligerant2.joueur.Nom}}
                </td>  
                <td>
                    {{game.belligerant1.compo.guilde.nom}} vs {{game.belligerant2.compo.guilde.nom}}
                </td>
                <td>
                    {{game.belligerant1.compo.code}} vs {{game.belligerant2.compo.code}}
                </td>
                <td>
                    {{game.date|date("d/m/Y")}}
                </td>
                <td>
                    <a href="{{ path('resultat_edit', {'id' : game.id}) }}">Modifier</a>
                </td>
            </tr>
        {% endfor %}


    </table>

<a href="{{ path('resultat_edit') }}">Créer</a>
</div>
{% endblock %}